src/Entity/Comment.php
<?php

namespace App\Entity;

use App\Repository\CommentRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CommentRepository::class)
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="text")
     */
    private $comment;

    /**
     * @ORM\Column(type="integer")
     */
    private $rate;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Author;

    /**
     * @ORM\ManyToOne(targetEntity=Episode::class, inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $episode;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setComment(string $comment): self
    {
        $this->comment = $comment;

        return $this;
    }

    public function getRate(): ?int
    {
        return $this->rate;
    }

    public function setRate(int $rate): self
    {
        $this->rate = $rate;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->Author;
    }

    public function setAuthor(?User $Author): self
    {
        $this->Author = $Author;

        return $this;
    }

    public function getEpisode(): ?Episode
    {
        return $this->episode;
    }

    public function setEpisode(?Episode $episode): self
    {
        $this->episode = $episode;

        return $this;
    }
}

src/Form/CommentType.php
<?php

namespace App\Form;

use App\Entity\Comment;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommentType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('Author', null, ['choice_label' => 'username'])
            ->add('episode', null, ['choice_label' => 'title'])
            ->add('rate')
            ->add('comment');
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Comment::class,
        ]);
    }
}

src/Controller/CommentController.php
<?php

namespace App\Controller;

use App\Entity\Comment;
use App\Form\CommentType;
use App\Repository\CommentRepository;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Security\Core\Exception\AccessDeniedException;

/**
 * @Route("/comment")
 */
class CommentController extends AbstractController
{
    /**
     * @Route("/", name="comment_index", methods={"GET"})
     */
    public function index(CommentRepository $commentRepository): Response
    {
        return $this->render('comment/index.html.twig', [
            'comments' => $commentRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="comment_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $comment = new Comment();
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($comment);
            $entityManager->flush();

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('comment/new.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comment_show", methods={"GET"})
     */
    public function show(Comment $comment): Response
    {


        return $this->render('comment/show.html.twig', [
            'comment' => $comment,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="comment_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Comment $comment): Response
    {
        $form = $this->createForm(CommentType::class, $comment);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('comment_index');
        }

        return $this->render('comment/edit.html.twig', [
            'comment' => $comment,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="comment_delete", methods={"POST"})
     * @IsGranted("ROLE_CONTRIBUTOR")
     */
    public function delete(Request $request, Comment $comment): Response
    {
        // Check wether the logged in user is the owner of the comment
        if (!($this->getUser() == $comment->getAuthor())) {
            // If not the owner, throws a 403 Access Denied exception
            throw new AccessDeniedException('Only the owner can delete the comment!');
        }
        if ($this->isCsrfTokenValid('delete' . $comment->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($comment);
            $entityManager->flush();
        }

        return $this->redirectToRoute('comment_index');
    }
}

templates/comment/_delete_form.html.twig
<form method="post" action="{{ path('comment_delete', {'id': comment.id}) }}" onsubmit="return confirm('Êtes-vous sûr(e) de voulir supprimer ce commentaire?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ comment.id) }}">
    {% if app.user or is_granted("ROLE_ADMIN") %}
        <button class="btn">Delete</button>
    {% endif %}
</form>

templates/comment/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/comment/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Comment{% endblock %}

{% block body %}
    <h1>Edit Comment</h1>

    {{ include('comment/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('comment_index') }}">back to list</a>

  {% if app.user %}
    {% if is_granted('ROLE_ADMIN') or app.user.email == comment.author.email %}
      {{ include('comment/_delete_form.html.twig') }}
    {% endif %}
  {% endif %}
{% endblock %}

templates/comment/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Comment index
{% endblock %}

{% block body %}
  <h1>
    Comment index
  </h1>

  <table class="table">
    <thead>
      <tr>
        <th>
          Id
        </th>
        <th>
          Comment
        </th>
        <th>
          Rate
        </th>
        <th>
          actions
        </th>
      </tr>
    </thead>
    <tbody>
      {% for comment in comments %}
        <tr>
          <td>
            {{ comment.id }}
          </td>
          <td>
            {{ comment.comment }}
          </td>
          <td>
            {{ comment.rate }}
          </td>
          <td>
            <a href="{{
              path(
                'comment_show',
                {
                  id: comment.id
                }
              )
              }}">
              show
            </a>
            {% if app.user %}
              {% if
                is_granted('ROLE_ADMIN')
                  or app.user.email == comment.author.email %}
                <a href="{{
                  path(
                    'comment_edit',
                    {
                      id: comment.id
                    }
                  )
                  }}">
                  edit
                </a>
              {% endif %}
            {% endif %}
          </td>
        </tr>
      {% else %}
        <tr>
          <td colspan="4">
            no records found
          </td>
        </tr>
      {% endfor %}
    </tbody>
  </table>

  <a href="{{ path('comment_new') }}">Create new</a>
{% endblock %}

templates/comment/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Comment{% endblock %}

{% block body %}
    <h1>Create new Comment</h1>

    {{ include('comment/_form.html.twig') }}

    <a href="{{ path('comment_index') }}">back to list</a>
{% endblock %}

templates/comment/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}
  Comment
{% endblock %}

{% block body %}
  <h1>
    Comment
  </h1>

  <table class="table">
    <tbody>
      <tr>
        <th>
          Id
        </th>
        <td>
          {{ comment.id }}
        </td>
      </tr>
      <tr>
        <th>
          Comment
        </th>
        <td>
          {{ comment.comment }}
        </td>
      </tr>
      <tr>
        <th>
          Rate
        </th>
        <td>
          {{ comment.rate }}
        </td>
      </tr>
    </tbody>
  </table>

  <a href="{{ path('comment_index') }}">back to list</a>

  <a href="{{
    path(
      'comment_edit',
      {
        id: comment.id
      }
    )
    }}">
    edit
  </a>

  {% if app.user %}
    {% if is_granted('ROLE_ADMIN') or app.user.email == comment.author.email %}
      {{ include('comment/_delete_form.html.twig') }}
    {% endif %}
  {% endif %}
{% endblock %}